Traceback (most recent call last):
  File "C:\Users\richa\AppData\Roaming\Python\Python311\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\ProgramData\anaconda3\Lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\ProgramData\anaconda3\Lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\ProgramData\anaconda3\Lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from phasepy import component, mixture, preos, vdweos, rkseos,virialgamma

water = component(name='water',Tc=647.13, Pc=220.55, Zc=0.229, Vc=55.948, w=0.344861,
                  GC={'H2O':1}, ri=0.92, qi=1.4, Mw=18)
ethanol = component(name='ethanol',Tc=514, Pc=61.37, Zc=0.241, Vc=168, w=0.643558, 
                    GC={'CH3':1,'CH2':1,'OH(P)':1},ri=2.1055, qi=1.972, Mw=46.07)

mix = mixture(water,ethanol)
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [1;32mIn[4], line 1[0m
[1;32m----> 1[0m [38;5;28;01mfrom[39;00m [38;5;21;01mphasepy[39;00m [38;5;28;01mimport[39;00m component, mixture, preos, vdweos, rkseos,virialgamma
[0;32m      3[0m water [38;5;241m=[39m component(name[38;5;241m=[39m[38;5;124m'[39m[38;5;124mwater[39m[38;5;124m'[39m,Tc[38;5;241m=[39m[38;5;241m647.13[39m, Pc[38;5;241m=[39m[38;5;241m220.55[39m, Zc[38;5;241m=[39m[38;5;241m0.229[39m, Vc[38;5;241m=[39m[38;5;241m55.948[39m, w[38;5;241m=[39m[38;5;241m0.344861[39m,
[0;32m      4[0m                   GC[38;5;241m=[39m{[38;5;124m'[39m[38;5;124mH2O[39m[38;5;124m'[39m:[38;5;241m1[39m}, ri[38;5;241m=[39m[38;5;241m0.92[39m, qi[38;5;241m=[39m[38;5;241m1.4[39m, Mw[38;5;241m=[39m[38;5;241m18[39m)
[0;32m      5[0m ethanol [38;5;241m=[39m component(name[38;5;241m=[39m[38;5;124m'[39m[38;5;124methanol[39m[38;5;124m'[39m,Tc[38;5;241m=[39m[38;5;241m514[39m, Pc[38;5;241m=[39m[38;5;241m61.37[39m, Zc[38;5;241m=[39m[38;5;241m0.241[39m, Vc[38;5;241m=[39m[38;5;241m168[39m, w[38;5;241m=[39m[38;5;241m0.643558[39m, 
[0;32m      6[0m                     GC[38;5;241m=[39m{[38;5;124m'[39m[38;5;124mCH3[39m[38;5;124m'[39m:[38;5;241m1[39m,[38;5;124m'[39m[38;5;124mCH2[39m[38;5;124m'[39m:[38;5;241m1[39m,[38;5;124m'[39m[38;5;124mOH(P)[39m[38;5;124m'[39m:[38;5;241m1[39m},ri[38;5;241m=[39m[38;5;241m2.1055[39m, qi[38;5;241m=[39m[38;5;241m1.972[39m, Mw[38;5;241m=[39m[38;5;241m46.07[39m)

[1;31mModuleNotFoundError[0m: No module named 'phasepy'
ModuleNotFoundError: No module named 'phasepy'

